### PR TITLE
added functionality behind ChooseYourUniversityWindow

### PR DESCRIPTION
**Pull request by werixx1**
-uni is now saved to the student data:3
-i also added University property and updated constructor in Student class
mebtwbtw

### CODE REVIEW

**Review by cleriselune — APPROVED** [review]
werson as always working at the weirdest hours out there
(go to eep soon pookie<3)
image

**Comment by werixx1** [comment]
im locking in vro🙂‍↕️🙂‍↕️🙂‍↕️

**Comment by cleriselune** [comment]
LOCK IN TOMMOROW >:(

**Comment by werixx1** [comment]
lalalala cant hear you😎

**Pull request merged**
