### PR TITLE
working log in button and list of students

### PR DESCRIPTION
**Pull request by cleriselune**
PLEASE CHCECK ALL OF YOU IF IT ACTUALLY WORKS ON YOUR COMPUTERS BEFORE ACCEPTING CAUSE IT WORKS ON MINE :3 

in the class StudentData u have first 5 students and all of their info + usernames and password (its the same one for all accounts; u can change usernames and passwords idc) and try to log in and see if it works for your account<3

image

### CODE REVIEW

**Review by werixx1 — COMMENTED** [review]
works flawlessly on mine, but we can wait for others to try it out before merging:D epic work!!

you

**Comment by cleriselune** [comment]
I ADDED JSON SO THE FIRST COMMENT IS NOT REALLY TRUE ANYMORE :333333
but to test this you can:
1. make your own account in sign in
2. close the app after it takes you to the quiz page
3. see if the json file was uploaded with your account data 
thats all <3

**Comment by yola512** [comment]
all good :) great job <3

**Comment by cleriselune** [comment]
fixed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Review by judzia — APPROVED** [review]
Looks amazing 🩷

**Pull request merged**
